#
# Default values

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  name: mrmat-python-api-fastapi-sa

pod:
  name: mrmat-python-api-fastapi
  replicas: 2
  repository: registry:5000/mrmat-python-api-fastapi
  imagePullPolicy: IfNotPresent
  port: 8000

service:
  name: mrmat-python-api-fastapi-svc
  port: 80

httproute:
  enabled: true
  name: mrmat-python-api-fastapi-httproute
  hostnames:
  - mrmat-python-api-fastapi.covenant.local
  parents:
  - name: edge-ingress
    namespace: edge

ingress:
  enabled: false
  name: mrmat-python-api-fastapi-ing
  className: ""
  annotations: { }
    # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
  - host: mrmat-python-api-fastapi.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: [ ]
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
