#
# Default values for MrMat :: Python API FastAPI

cluster:
  mesh: istio
  gateway_api: true
  name: cluster
  domain: k8s

sa:
  name: sa-mpafastapi

pod:
  name: mpafastapi
  replicas: 1
  repository: registry:5000/mrmat-python-api-fastapi
  imagePullPolicy: Always
  port: 8000

svc:
  name: svc-mpafastapi
  port: 80

edge:
  ns: edge
  name: edge-ingress
  kind: istio-gateway-api

route:
  hostname: mpafastapi

ingress:
  hostname: mpafastapi

config:
  db_url: "sqlite:////data/db.sqlite3"
