#
# Default values for MrMat :: Python API FastAPI

sa:
  name: sa-mpafastapi

pod:
  name: mpafastapi
  replicas: 1
  repository: registry:5000/mrmat-python-api-fastapi
  imagePullPolicy: Always
  port: 8000

svc:
  name: svc-mpafastapi
  port: 80

edge:
  ns: edge
  name: edge-ingress
  kind: istio-gateway-api

route:
  enabled: false
  name: route-mpafastapi
  hostnames:
  - mpafastapi.nostromo.k8s
  parents:
  - name: edge-ingress
    namespace: edge

istio: ambient

ingress:
  enabled: false
  hostname: mpafastapi.nostromo.k8s

config:
  db_url: "sqlite:////data/db.sqlite3"
