#
# Default values for MrMat :: Python API FastAPI

sa:
  name: sa-mpafastapi

pod:
  name: mpafastapi
  replicas: 1
  repository: registry:5000/mrmat-python-api-fastapi
  imagePullPolicy: Always
  port: 8000

svc:
  name: svc-mpafastapi
  port: 80

route:
  enabled: true
  name: route-mpafastapi
  hostnames:
  - mpafastapi.covenant.local
  parents:
  - name: edge-ingress
    namespace: edge

config:
  db_url: "sqlite:///data/db.sqlite"
