### GET Owners
GET http://localhost:8000/api/platform/v1/owners

### GET resources
GET http://localhost:8000/api/platform/v1/resources

### Create Owner
POST http://localhost:8000/api/platform/v1/owners
Content-Type: application/json

{
    "name": "MrMat"
}

> {%
    const owner_uid = jsonPath(response.body, ".owner_uid")
 %}

###
