{{- if eq .Values.edge.kind "gateway-api" -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route-mpafastapi
  labels:
    app.kubernetes.io/name: route-mpafastapi
    {{ include "common.labels" . | nindent 4 }}
spec:
  hostnames:
  - {{ .Values.route.hostname }}.{{ .Values.cluster.name }}.{{ .Values.cluster.domain }}
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.edge.name }}
    namespace: {{ .Values.edge.ns }}
    sectionName: mpafastapi
  rules:
  - backendRefs:
    - kind: Service
      name: {{ .Values.svc.name }}
      port: {{ .Values.svc.port }}
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
{{- end -}}
