{{- if eq .Values.edge.kind "ingress" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mpafastapi
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: https
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}.{{ .Values.cluster.name }}.{{ .Values.cluster.domain }}
    secretName: mpafastapi-cert
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.svc.name }}
            port:
              number: 80
{{- end }}