{{- if .Values.httproute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.httproute.name }}
  labels:
    app: {{ .Values.pod.name }}
    version: {{ .Chart.AppVersion }}
    app.kubernetes.io/name: {{ .Values.httproute.name }}
    app.kubernetes.io/part-of: mrmat-python-api-fastapi
spec:
  hostnames:
  {{- range .Values.httproute.hostnames }}
  - {{ . | quote }}
  {{- end }}
  parentRefs:
  {{- range .Values.httproute.parents }}
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .name }}
    namespace: {{ .namespace }}
    sectionName: mrmat-python-api-fastapi
  {{- end }}
  rules:
  - backendRefs:
    - kind: Service
      name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
{{- end -}}
