apiVersion: v1
kind: Secret
metadata:
  name: config-mpafastapi
  labels:
    app.kubernetes.io/name: config-mpafastapi
    {{ include "common.labels" . | nindent 4 }}
stringData:
  app_config.json: |-
    { "db_url": {{ .Values.config.db_url | quote }} }
