apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    app: {{ .Values.pod.name }}
    version: {{ .Chart.AppVersion }}
    app.kubernetes.io/name: {{ .Values.serviceAccount.name }}
    app.kubernetes.io/part-of: mrmat-python-api-fastapi
automountServiceAccountToken: true
