apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.pod.name }}
    version: {{ .Chart.AppVersion }}
    app.kubernetes.io/name: {{ .Values.service.name }}
    app.kubernetes.io/part-of: mrmat-python-api-fastapi
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.pod.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.pod.name }}
    version: {{ .Chart.AppVersion }}
